### ISSUE TITLE
App crashes on opening child profile

### ISSUE THREAD

**Issue by cozej4** [OpenSRP/opensrp-client-chw-hf#48]
The App crashes on opening child profile from any register.

**Comment by cozej4** [comment]
![device-2020-02-18-172913](https://user-images.githubusercontent.com/9714534/74745240-9fdd8400-5274-11ea-8653-877f41b8b2e3.png)
Clicking the child to view child profile leads to app crash

**Comment by cozej4** [comment]
Error log
<img width="1600" alt="Screen Shot 2020-02-18 at 5 34 34 PM" src="https://user-images.githubusercontent.com/9714534/74745454-fc40a380-5274-11ea-8d2e-a883d6ba58d1.png">

**Comment by allan-on** [comment]
Hi @cozej4 and @msschroeder. Having looked into this, I couldn't recreate the crashing of the app by loading any of the children's profiles. 
The specific record seems to have been deleted from the register. The bug seems to be related to a view defined in `chw-core`. I'll be on the lookout for this error.

**Comment by msschroeder** [comment]
lgtm.
